### ISSUE TITLE
Does this still build?

### ISSUE THREAD

**Issue by Chuhtra** [d99kris/spacy-cpp#10] opened 2022-02-26 17:08 UTC
Hi!

I want to use this library in an app but I can't get it to work. 

The first obstacle was two `error: 'runtime_error' is not a member of 'std'` thrown in `src/spacy/spacy.cpp` file. I overcame this by adding `#include <stdexcept>` in this file. 

The thing is that even after this, I can't seem to be able to use it in my project. `#include <spacy/spacy>` throws `No such file or directory error`.

My `CMakeLists.txt` is 

```cmake
cmake_minimum_required(VERSION 3.12)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# create project
project(myapp VERSION 0.1)

# add executable
add_executable(hello src/main.cpp)

# add CPM
set(CPM_DOWNLOAD_LOCATION "${CMAKE_BINARY_DIR}/cmake/CPM.cmake")

if(NOT (EXISTS ${CPM_DOWNLOAD_LOCATION}))
    message(STATUS "Downloading CPM.cmake")
    file(DOWNLOAD https://github.com/TheLartians/CPM.cmake/releases/latest/download/CPM.cmake ${CPM_DOWNLOAD_LOCATION})
endif()

include(${CPM_DOWNLOAD_LOCATION})

# add spacy
CPMAddPackage(
  NAME spacy
  GITHUB_REPOSITORY d99kris/spacy-cpp
  VERSION 1.04
)
target_link_libraries(hello PUBLIC spacy)


```

I would appreciate it if you gave me some insight.

**Comment by d99kris** [comment] 2022-02-27 05:16
Hi!

Thanks for reporting the issue and pointing out the missing header include.

I found some issues in the `CMakeLists.txt` file of `spacy-cpp` which I have addressed in above commit, along with adding the missing include.

Your `CMakeLists.txt` now works for me, with the minor adjustment of changing it to use latest spacy-cpp release `1.05` instead of `1.04`.

I tested on Linux (`Ubuntu 20.04`) with compiler `g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`.

Please let me know if you are still seeing build problems using latest `spacy-cpp`. If yes, feel free to re-open this issue and please provide which OS/distro and compiler is used. Also the full output from `cmake` and `make` may be useful.

Thanks!

**Comment by d99kris** [comment] 2022-02-27 05:21
Just to add on, the cpp file I used with your `CMakeLists.txt` was `src/main.cpp` with the following content:
```c++
#include <iostream>
#include <spacy/spacy>

int main()
{
  Spacy::Spacy spacy;
  auto nlp = spacy.load("en_core_web_sm");
  auto doc = nlp.parse("This is a sentence.");
  for (auto& token : doc.tokens())
    std::cout << token.text() << " [" << token.pos_() << "]\n";
}
```

**Comment by Chuhtra** [comment] 2022-02-27 18:00
Hi, thank you for the swift response! Followed your points, but still, "no such file or directory". I am using Manjaro Linux and g++ 11.1.0. Here is the `cmake` result:

```
[stelios@Volund myapp]$ mkdir build && cd build && cmake ..
-- The C compiler identification is GNU 11.1.0
-- The CXX compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Downloading CPM.cmake
-- CPM: adding package spacy@1.05 (v1.05)
-- Found PythonLibs: /usr/lib/libpython3.10.so (found suitable version "3.10.2", minimum required is "3") 
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.10.2", minimum required is "3") 
-- Build tests: OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/path/to/my/app/myapp/build
```

And then `make`:

```
[stelios@Volund build]$ make
[  7%] Building CXX object _deps/spacy-build/CMakeFiles/spacy.dir/src/spacy/attrs.cpp.o
[ 15%] Building CXX object _deps/spacy-build/CMakeFiles/spacy.dir/src/spacy/nlp.cpp.o
[ 23%] Building CXX object _deps/spacy-build/CMakeFiles/spacy.dir/src/spacy/python.cpp.o
[ 30%] Building CXX object _deps/spacy-build/CMakeFiles/spacy.dir/src/spacy/span.cpp.o
[ 38%] Building CXX object _deps/spacy-build/CMakeFiles/spacy.dir/src/spacy/doc.cpp.o
[ 46%] Building CXX object _deps/spacy-build/CMakeFiles/spacy.dir/src/spacy/pyobjectptr.cpp.o
[ 53%] Building CXX object _deps/spacy-build/CMakeFiles/spacy.dir/src/spacy/spacy.cpp.o
[ 61%] Building CXX object _deps/spacy-build/CMakeFiles/spacy.dir/src/spacy/stringstore.cpp.o
[ 69%] Building CXX object _deps/spacy-build/CMakeFiles/spacy.dir/src/spacy/token.cpp.o
[ 76%] Building CXX object _deps/spacy-build/CMakeFiles/spacy.dir/src/spacy/vocab.cpp.o
[ 84%] Linking CXX shared library libspacy.so
[ 84%] Built target spacy
[ 92%] Building CXX object CMakeFiles/myapp.dir/src/main.cpp.o
/home/path/to/my/app/myapp/src/main.cpp:4:10: fatal error: spacy/spacy: No such file or directory
    4 | #include <spacy/spacy>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/myapp.dir/build.make:76: CMakeFiles/myapp.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/myapp.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Closed** 2022-02-28 11:10 UTC

**Comment by d99kris** [comment] 2022-02-28 11:21
Hi! Thanks for providing additional details. I was able to reproduce the original problem now.

With the above commit I hope the issue should finally be fixed. Just point to `spacy-cpp` `VERSION 1.06`.

**Comment by Chuhtra** [comment] 2022-02-28 11:53
Yes, it works now! Thank you!
